### PR TITLE
draft GoOpWrapper.swift based off wrappers.go

### PR DESCRIPTION
**Pull request by johndpope**
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/op/wrappers.go

### CODE REVIEW

**Comment by rxwei** [comment]
Hi @johndpope , I am not actively maintaining this repo and I'm not quite familiar with what you are working on. Are the Swift files in here generated or hand-coded?

**Comment by johndpope** [comment]
The TF_xyz are wrappers around the C API.
they were generated via xcode.

screen shot 2017-06-03 at 9 44 03 am

The GoXyz files are direct hand written ports of golang code.

There's a helper class 
GeneratedOps.swift that builds a monolithic GoOpWrapper based off the ops.pb proto buffer file / and stencilkit.

this corresponds to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/op/wrappers.go


https://github.com/johndpope/tensorflow/blob/256ee4fb4b95c050275acc433005bc75b7e023a7/tensorflow/swift/Sources/GenerateOps.swift

I get you've lost interest in getting tensorflow to run in swift - but I thought maybe I could  spark your interest.

The last missing piece of code is porting GoTensor.swift .
I found some code in protobuffers to help decode / 'reflect' the types .

Will have a crack over coming days.

**Comment by rxwei** [comment]
I appreciate your work! Hand-coding is great and is definitely the way to go, but the ported code seems way off the [Swift API convention](https://swift.org/documentation/api-design-guidelines/). Perhaps you could refactor it a bit?

**Comment by johndpope** [comment]
Please excuse capital letters. I deliberately yielded to the golang format as much as possible while codebase is still in it's infancy. It's suppose to help cross check things against  google's 'supported' golang code with code created by contributors. ie if it has a capital letter / it is remotely/partially supported. As more developers rally to this codebase - then we can drop the golang syntax or ditch this once we hit a v1.0

I wrote these notes in readme.
https://github.com/johndpope/tensorflow/tree/master/tensorflow/swift

think of this code as swift 2 - and a giant refactoring / swift 3/4 with breaking changes (every call will be lower case) can take place eventually. Right now - the capital letters are helping me port / cross check code. 

I do have my eyes set on a python port - 
https://www.tensorflow.org/api_docs/python/ 

you might be interested in some code to treewalk golang files in swift
https://github.com/johndpope/Antlr-Swift-Runtime/tree/master/Test/Test
I did attempt to walk python files - but there's a bug with antlr 'reserved characters'
https://github.com/antlr/antlr4/issues/1851

**Comment by rxwei** [comment]
Oh, thanks a lot for clarifying!

**Comment by johndpope** [comment]
fyi - current brain dump on codebase 
https://docs.google.com/spreadsheets/d/1-B61huuIoKqyjS7dUb6GGZm5bt1gVcA58uxAKnojdDU/edit#gid=0

**Comment by rxwei** [comment]
Looks good. I would like to contribute to this, but my schedule unfortunately doesn't allow it. Feel free to let me know if you'd like me to transfer ownership of the fork.

**Pull request merged**
